import json

with open('../../config/error_codes.json', 'r') as f:
    data = json.load(f)

header = '''/**
 * @file:    error_code.h
 * @author:  Luke
 * @brief:   error code management header file, generated by gen_error_code.py
 * @warning: Do not modify this file manually.
 */

 /**
 *   32位整型错误码，结构如下：
 *   | 位数 | 含义 | 说明 |
 *   |-----------|--------------|---------------------|
 *   | 31..24 | 模块号 | 8位，支持256模块 |
 *   | 23..16 | 子模块号 | 8位，支持256子模块 |
 *   | 15..0 | 错误编号 | 16位，支持65536种错误 |
 */

#ifndef ERROR_CODE_H
#define ERROR_CODE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ERR_MODULE_SHIFT      24
#define ERR_SUBMODULE_SHIFT   16
#define ERR_CODE_MASK         0xFFFF

#define MAKE_ERROR_CODE(module, submodule, code) \\
    (((uint32_t)(module) << ERR_MODULE_SHIFT) | ((uint32_t)(submodule) << ERR_SUBMODULE_SHIFT) | ((uint32_t)(code) & ERR_CODE_MASK))

#define GET_MODULE_FROM_ERR(err)     (((err) >> ERR_MODULE_SHIFT) & 0xFF)
#define GET_SUBMODULE_FROM_ERR(err)  (((err) >> ERR_SUBMODULE_SHIFT) & 0xFF)
#define GET_CODE_FROM_ERR(err)       ((err) & ERR_CODE_MASK)

'''

footer = '''
const char* sx_error_code_to_str(uint32_t code);

#ifdef __cplusplus
}
#endif

#endif // ERROR_CODE_H
'''

c_impl = '''/**
 * @file:    error_code.c
 * @author:  Luke
 * @brief:   error code management source file, generated by gen_error_code.py
 * @warning: Do not modify this file manually.
 */

#include "common/error_code.h"

const char* sx_error_code_to_str(uint32_t code) {
    switch (code) {
'''

# 生成宏定义
for mod in data['modules']:
    header += f'// Module: {mod["name"]}\n'
    header += f'#define MODULE_{mod["name"]} {mod["id"]}\n'
    for sub in mod['submodules']:
        header += f'#define SUBMOD_{mod["name"]}_{sub["name"]} {sub["id"]}\n'
        for err in sub['errors']:
            macro = f'SX_ERR_{mod["name"]}_{sub["name"]}_{err["name"]}'
            header += f'#define {macro} MAKE_ERROR_CODE(MODULE_{mod["name"]}, SUBMOD_{mod["name"]}_{sub["name"]}, {err["code"]})\n'
            c_impl += f'        case {macro}: return "{err["msg"]}";\n'
    header += '\n'

header += footer
c_impl += '''        default: return "Unrecognized error code";
    }
}
'''

with open('../../src/common/include/common/error_code.h', 'w') as f:
    f.write(header)

with open('../../src/common/error_code.c', 'w') as f:
    f.write(c_impl)
    