/**
 * @file:    error_code.h
 * @author:  Luke
 * @brief:   error code management header file, generated by gen_error_code.py
 * @warning: Do not modify this file manually.
 */

 /**
 *   32位整型错误码，结构如下：
 *   | 位数 | 含义 | 说明 |
 *   |-----------|--------------|---------------------|
 *   | 31..24 | 模块号 | 8位，支持256模块 |
 *   | 23..16 | 子模块号 | 8位，支持256子模块 |
 *   | 15..0 | 错误编号 | 16位，支持65536种错误 |
 */

#ifndef ERROR_CODE_H
#define ERROR_CODE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ERR_MODULE_SHIFT      24
#define ERR_SUBMODULE_SHIFT   16
#define ERR_CODE_MASK         0xFFFF

#define MAKE_ERROR_CODE(module, submodule, code) \
    (((uint32_t)(module) << ERR_MODULE_SHIFT) | ((uint32_t)(submodule) << ERR_SUBMODULE_SHIFT) | ((uint32_t)(code) & ERR_CODE_MASK))

#define GET_MODULE_FROM_ERR(err)     (((err) >> ERR_MODULE_SHIFT) & 0xFF)
#define GET_SUBMODULE_FROM_ERR(err)  (((err) >> ERR_SUBMODULE_SHIFT) & 0xFF)
#define GET_CODE_FROM_ERR(err)       ((err) & ERR_CODE_MASK)

// Module: SEEKER
#define MODULE_SEEKER 0
#define SUBMOD_SEEKER_COMMON 0
#define SX_ERR_SEEKER_COMMON_OK MAKE_ERROR_CODE(MODULE_SEEKER, SUBMOD_SEEKER_COMMON, 0)
#define SX_ERR_SEEKER_COMMON_UNKNOWN MAKE_ERROR_CODE(MODULE_SEEKER, SUBMOD_SEEKER_COMMON, 1)
#define SX_ERR_SEEKER_COMMON_INVALID_PARAM MAKE_ERROR_CODE(MODULE_SEEKER, SUBMOD_SEEKER_COMMON, 2)
#define SUBMOD_SEEKER_MODULE1 1
#define SX_ERR_SEEKER_MODULE1_OK MAKE_ERROR_CODE(MODULE_SEEKER, SUBMOD_SEEKER_MODULE1, 0)
#define SUBMOD_SEEKER_MODULE2 2
#define SX_ERR_SEEKER_MODULE2_OK MAKE_ERROR_CODE(MODULE_SEEKER, SUBMOD_SEEKER_MODULE2, 0)


const char* sx_error_code_to_str(uint32_t code);

#ifdef __cplusplus
}
#endif

#endif // ERROR_CODE_H
