/**
 * @file:    error_code.c
 * @author:  Luke
 * @brief:   error code management source file, generated by gen_error_code.py
 * @warning: Do not modify this file manually.
 */

#include "common/error_code.h"

const char* sx_error_code_to_str(uint32_t code) {
    switch (code) {
        case SX_ERR_SEEKER_COMMON_OK: return "No error";
        case SX_ERR_SEEKER_COMMON_UNKNOWN: return "Unknown error";
        case SX_ERR_SEEKER_COMMON_INVALID_PARAM: return "Invalid parameter";
        case SX_ERR_SEEKER_MODULE1_OK: return "No error";
        case SX_ERR_SEEKER_MODULE2_OK: return "No error";
        default: return "Unrecognized error code";
    }
}
